const sampleIr = `define i32 @combined(i32 %x) {
entry:
  %a = add i32 4, 5
  %b = mul i32 %x, 8
  %c = udiv i32 %b, 4
  %d = add i32 %c, %a
  ret i32 %d
}`;

const inputIr = document.querySelector("#inputIr");
const outputIr = document.querySelector("#outputIr");
const runButton = document.querySelector("#runButton");
const resetButton = document.querySelector("#resetButton");
const changeCount = document.querySelector("#changeCount");
const changeList = document.querySelector("#changeList");
const summaryText = document.querySelector("#summaryText");

inputIr.value = sampleIr;
outputIr.textContent = sampleIr;

function setChanges(items) {
  changeList.innerHTML = "";

  items.forEach((text) => {
    const item = document.createElement("li");
    item.textContent = text;
    changeList.appendChild(item);
  });
}

function countChangedLines(before, after) {
  const beforeLines = before.split("\n");
  const afterLines = after.split("\n");
  const total = Math.max(beforeLines.length, afterLines.length);
  let changed = 0;

  for (let index = 0; index < total; index += 1) {
    if ((beforeLines[index] || "") !== (afterLines[index] || "")) {
      changed += 1;
    }
  }

  return changed;
}

async function runOptimizer() {
  const ir = inputIr.value;

  runButton.disabled = true;
  runButton.textContent = "Running";
  changeCount.textContent = "Running";
  summaryText.textContent = "Running the LLVM pass with opt.";
  setChanges([]);

  try {
    const response = await fetch("/api/optimize", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ir }),
    });
    const payload = await response.json();

    if (!response.ok) {
      throw new Error(payload.error || "Optimization failed.");
    }

    outputIr.textContent = payload.optimizedIr;

    const changedLines = countChangedLines(ir, payload.optimizedIr);
    changeCount.textContent = changedLines === 1 ? "1 line changed" : `${changedLines} lines changed`;
    summaryText.textContent = "The optimized IR below was generated by the compiled LLVM pass.";
    setChanges([
      "Input was sent to the local Node server.",
      "The server ran opt with ConstFoldStrengthReducePass.so.",
      "The transformed IR was returned from the real LLVM pipeline.",
    ]);
  } catch (error) {
    outputIr.textContent = error.message;
    changeCount.textContent = "Failed";
    summaryText.textContent = "The optimizer could not run for this input.";
    setChanges([
      "Check that the page is opened through npm start, not as a raw file.",
      "Check that the LLVM pass has been built in the build directory.",
      "Check that the input is valid LLVM IR.",
    ]);
  } finally {
    runButton.disabled = false;
    runButton.textContent = "Run opt";
  }
}

runButton.addEventListener("click", runOptimizer);
resetButton.addEventListener("click", () => {
  inputIr.value = sampleIr;
  outputIr.textContent = sampleIr;
  changeCount.textContent = "Ready";
  summaryText.textContent = "Run the pass to see the optimized LLVM IR.";
  setChanges([]);
});
